language: rust
os:
  - linux
  - windows
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
script:
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
