[package]
name = "parallel-sh"
version = "0.1.1"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
description = "Execute commands in parallel"
readme = "README.md"
license = "MIT"
homepage = "https://crates.io/crates/parallel-sh"
repository = "https://github.com/thyrc/parallel-sh"
keywords = ["cli", "parallel", "concurrency", "shell"]
categories = ["command-line-utilities", "concurrency"]
exclude = [".github", ".travis.yml"]

[badges]
travis-ci = { repository = "thyrc/parallel-sh" }

[dependencies]
log = "0.4"
num_cpus = "1"
simplelog = "0.10"

[dependencies.chrono]
version = "0.4"
default-features = false

[dependencies.clap]
version = "2"
default-features = false

[profile.release]
panic = "abort"
lto = true
debug = false
